<?php

return [
    // ================= GOVERNMENT =================
    [
        'short' => 'OFC',
        'full' => 'Ordnance Factory Chanda',
        'category' => 'government',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=OFC',
        'work' => 'Civil & High-Voltage Electrical Infrastructure Contract',
        'year' => '2024',
        'location' => 'Chanda, Maharashtra',
        'verified' => true,
        'featured' => true,
    ],
    [
        'short' => 'CPWD',
        'full' => 'Central Public Works Department',
        'category' => 'government',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=CPWD',
        'work' => 'Administrative Building Modernization Project',
        'year' => '2021',
        'location' => 'New Delhi',
        'verified' => true,
        'featured' => false,
    ],
    [
        'short' => 'MES',
        'full' => 'Military Engineer Services',
        'category' => 'government',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=MES',
        'work' => 'Runway Repair & Airfield Lighting at Forward Base',
        'year' => '2022',
        'location' => 'Leh, Ladakh',
        'verified' => true,
        'featured' => false,
    ],
    [
        'short' => 'NHAI',
        'full' => 'National Highways Authority of India',
        'category' => 'government',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=NHAI',
        'work' => 'Four-Laning of NH-44 Stretch with Culverts & Drainage',
        'year' => '2023',
        'location' => 'Nagpur, Maharashtra',
        'verified' => true,
        'featured' => true,
    ],

    // ================= DEFENCE =================
    [
        'short' => 'BSF',
        'full' => 'Border Security Force',
        'category' => 'defence',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=BSF',
        'work' => 'Border Outpost Construction & Tactical Logistics',
        'year' => '2023',
        'location' => 'Jaisalmer, Rajasthan',
        'verified' => true,
        'featured' => true,
    ],
    [
        'short' => 'AR',
        'full' => 'Assam Rifles HQ',
        'category' => 'defence',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=AR',
        'work' => 'Quartermaster Complex & Defense Housing Units',
        'year' => '2023',
        'location' => 'Shillong, Meghalaya',
        'verified' => true,
        'featured' => true,
    ],
    [
        'short' => 'IAF',
        'full' => 'Indian Air Force Station',
        'category' => 'defence',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=IAF',
        'work' => 'Hangar Construction & Perimeter Security Electrification',
        'year' => '2024',
        'location' => 'Pune, Maharashtra',
        'verified' => true,
        'featured' => false,
    ],
    [
        'short' => 'IN',
        'full' => 'Indian Navy Dockyard',
        'category' => 'defence',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=IN',
        'work' => 'Dry Dock Civil Strengthening & Marine Electrical Works',
        'year' => '2022',
        'location' => 'Visakhapatnam, Andhra Pradesh',
        'verified' => true,
        'featured' => false,
    ],

    // ================= PSU =================
    [
        'short' => 'MSME',
        'full' => 'Ministry of MSME Technology Centre',
        'category' => 'psu',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=MSME',
        'work' => 'Tool Room Expansion & MEP Consultancy Works',
        'year' => '2024',
        'location' => 'Bhubaneswar, Odisha',
        'verified' => true,
        'featured' => true,
    ],
    [
        'short' => 'BHEL',
        'full' => 'Bharat Heavy Electricals Limited',
        'category' => 'psu',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=BHEL',
        'work' => 'Substation Erection & Transmission Line Foundation Works',
        'year' => '2023',
        'location' => 'Bhopal, Madhya Pradesh',
        'verified' => true,
        'featured' => false,
    ],
    [
        'short' => 'GAIL',
        'full' => 'GAIL India Limited',
        'category' => 'psu',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=GAIL',
        'work' => 'Pipeline Corridor Civil Works & Access Road Construction',
        'year' => '2021',
        'location' => 'Vijaipur, Madhya Pradesh',
        'verified' => true,
        'featured' => false,
    ],

    // ================= PRIVATE =================
    [
        'short' => 'L&T',
        'full' => 'Larsen & Toubro Heavy Engineering',
        'category' => 'private',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=L%26T',
        'work' => 'Subcontract for Industrial Machinery Installation',
        'year' => '2022',
        'location' => 'Hazira, Gujarat',
        'verified' => true,
        'featured' => true,
    ],
    [
        'short' => 'TATA',
        'full' => 'Tata Projects Limited',
        'category' => 'private',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=TATA',
        'work' => 'Warehouse Structural Steel & Pre-Engineered Building Works',
        'year' => '2023',
        'location' => 'Sanand, Gujarat',
        'verified' => true,
        'featured' => false,
    ],
    [
        'short' => 'ADANI',
        'full' => 'Adani Infrastructure & Ports',
        'category' => 'private',
        'logo' => 'https://placehold.co/100x100/0F172A/FFFFFF?text=ADANI',
        'work' => 'Port Storage Yard Civil Works & Internal Road Network',
        'year' => '2024',
        'location' => 'Mundra, Gujarat',
        'verified' => true,
        'featured' => true,
    ],
];
